---
- name: Install openjdk
  yum: 
    name: java-11-openjdk
    state: present
- name: Download jenkins repo
  ansible.builtin.get_url:
    url: "https://pkg.jenkins.io/redhat-stable/jenkins.repo"
    dest: /etc/yum.repos.d/jenkins.repo
    validate_certs: false

- name: import jenkins key 
  ansible.builtin.rpm_key:
    state: present
    key:   https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    validate_certs: false

- name: Install jenkins
  ansible.builtin.yum:
    name: jenkins
    state: present
- name: Start jenkins
  ansible.builtin.systemd:
    name: jenkins 
    state: started
- name: enable jenkins
  ansible.builtin.systemd:
    name: jenkins 
    enabled: true

- name: Sleep for 30 seconds and continue the play
  ansible.builtin.wait_for:
    timeout: 30
  delegate_to: localhost

- name: init password jenkins 
  ansible.builtin.shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password of jenkins
  debug: 
    var: result.stdout

