- name: "Cleaning the yum"
  command: "yum clean all" 

- name: "PHP Package Installation"
  yum:
    name: 'php'
    state: present

- name: "Installing the Apache Webserver"
  ansible.builtin.yum:
    name: httpd
    state: latest
  notify:
    - restart-httpd

- name: "Creating httpd.conf From template"
  template:
    src: httpd.conf.tmpl
    dest: "/etc/httpd/conf/httpd.conf"
  notify:
    - restart-httpd

- name: "Creating Virtualhost From template"
  template:
    src: virtualhost.conf.tmpl
    dest: "/etc/httpd/conf.d/{{domain_name}}.conf" 
  notify:
    - restart-httpd  

- name: "Document Root Creation"
  file:
    path: "/var/www/html/{{domain_name}}"
    state: directory
    owner: "{{httpd_user}}"
    group: "{{httpd_group}}"
  notify:
    - restart-httpd 

- name: "Creation Of test.php and test.html"
  copy: 
    src: "{{item}}"
    dest: "/var/www/html/{{domain_name}}"
    owner: "{{httpd_user}}"
    group: "{{httpd_group}}"
  with_items:
    - test.html
    - test.php
  notify:
    - restart-httpd

- name: "MariaDB Package Installation"
  yum:
    name: 
      - mariadb-server
      - python3-PyMySQL
    state: latest
  register: db

- name: "Restarting/Enabling The Service"
  service: 
    name: mariadb
    state: restarted
    enabled: true
  when: db.changed

- name: "Root Password Creation for MariaDB"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_password: ""
    user: "root"
    password: "{{root_password}}"
    host_all: true

- name: "Removal Of Anonymous User"
  mysql_user:
    login_user: "root"
    login_password: "{{root_password}}"
    user: ""
    state: absent
    host_all: true

- name: "Opening the firewall for HTTP and HTTPS traffic"
  firewalld:
    service: "{{item}}"
    immediate: yes
    permanent: yes
    zone: public
    state: enabled
  with_items:
    - http
    - https
