---

- name: "Updating All The Packages"
  apt:
    update_cache: true
    name:
      "*"
    state: latest

- name: "Apache Web Server Installation"
  apt:
    name:
      - apache2
    state: latest

- name: "Document Root Creation"
  file:
    path: "/var/www/html/{{domain_name}}/html"
    state: directory
    owner: "{{apache_user}}"
    group: "{{apache_group}}"
  notify:
    - restart-apache

- name: "PHP Package Installation"
  apt:
    name:
      - php
    state: latest

- name: "Creation Of test.php and test.html"
  copy:
    src: "{{item}}"
    dest: "/var/www/html/{{domain_name}}/html"
    owner: "{{apache_user}}"
    group: "{{apache_group}}"
  with_items:
    - test.html
    - test.php
  notify:
    - restart-apache

- name: "Creating Virtualhost From template"
  template:
    src: vhost.conf.tmpl
    dest: /etc/apache2/sites-available/{{ domain_name }}.conf
  notify:
    - restart-apache

- name: "Activating Virtual Host Configuration File"
  shell: /usr/sbin/a2ensite {{ domain_name }}.conf
  notify:
    - restart-apache

- name: "Disable default Apache site"
  shell: /usr/sbin/a2dissite 000-default.conf
  notify:
    - restart-apache


- name: "MariaDB Package Installation"
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: latest
  register: db

- name: "Restarting/Enabling The Service"
  service:
    name: mariadb
    state: restarted
    enabled: true
  when: db.changed

- name: "Root Password Creation for MariaDB"
  ignore_errors: true
  mysql_user:
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: 'localhost'
    login_password: ""
    user: "root"
    password: "{{root_password}}"
    host_all: true

- name: "Removal Of Anonymous User"
  mysql_user:
    login_user: "root"
    login_password: "{{root_password}}"
    user: ""
    state: absent
    host_all: true

